name: shiksha_dhra
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  appwrite: ^12.0.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.2.0
  responsiveness: ^1.2.8
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  supercharged: ^2.1.1
  talker_flutter: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/